disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
  - private_action

included:
  - SpendWise

excluded:
  - Pods
  - DerivedData
  - .build



identifier_name:
  min_length: 2
  max_length: 50

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

function_body_length:
  warning: 40
  error: 60

nesting:
  type_level: 3
  function_level: 3

reporter: "xcode"
